name: Test

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Virtualenv
        run: |
          python3 -m venv .venv
      - name: Activate Virtualenv
        run: |
          source .venv/bin/activate
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Install Development Dependencies
        run: |
          python -m pip install -r requirements.dev.txt
      - name: Run test suite
        run: |
          pytest
        env:
          STEAMSHIP_API_KEY: ${{ inputs.steamship_key_test }}
          STEAMSHIP_API_BASE: ${{ inputs.steamship_api_base_test }}
